// Generated by CoffeeScript 1.3.3

/*
    
======
put this in the top
======

addScript = {};


======
AddScript samples
======

<script type="text/javascript">
    addScript['jquery'] = 'http://code.jquery.com/jquery.min.js'; </script>


======
CALL BACK function Samples
======

window.twitterReady = ->
  console.log 'twitter is loaded'

window.jqueryReady = ->
  console.log 'jquery is loaded'
*/


(function() {
  var addScripts, fjs;

  fjs = document.getElementsByTagName('script')[0];

  /**
   *
   *  Add javascript ()
  */


  window.add = function(id, src, callback) {
    /**
     *
     * If the id exists, skip
    */

    var js;
    if (document.getElementsByTagName(id)) {
      void 0;
    }
    js = document.createElement('script');
    js.src = src;
    id && (js.id = id);
    fjs.parentNode.insertBefore(js, fjs);
    if (callback && typeof window[callback] === 'function') {
      return window[callback]();
    }
  };

  /**
   *
   * Loop through addScript obj, and addJs
  */


  addScripts = (function() {
    var id, src, _ref, _results;
    _ref = window.addScript;
    _results = [];
    for (id in _ref) {
      src = _ref[id];
      _results.push(add(id, src, id + 'Ready'));
    }
    return _results;
  })();

}).call(this);
